{"uuid": "a930bcf8-4056-4bab-a5db-7170e82234f0", "children": ["a0b65370-5dca-48de-aa8a-6e1a881cc365", "f1fa381a-3738-49d1-bcef-3c8e769aca62", "262df014-e282-417f-a743-05223731cc2b"], "befores": [{"name": "env", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/icsoc/.virtualenvs/pytest/lib/python3.6/site-packages/_pytest/fixtures.py\", line 782, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/icsoc/work/pytest/test/conftest.py\", line 18, in env\n    allure.environment(host=env_config['host']['domain']) # 测试报告中展示host\n"}, "start": 1548921964086, "stop": 1548921964086}], "start": 1548921964086, "stop": 1548921964177}